### PR TITLE
Smaler Docker image

### PR DESCRIPTION
**Pull request by lcasassa**

### CODE REVIEW

**Comment by lcasassa** [comment]
I can't assign this PR to you @svenwltr or any other.

**Comment by svenwltr** [comment]
@lcasassa I just saw the failing build. You need to update the Travis file too, since it uses this Docker image. I guess it will be enough to specify the stage with `--target` on the `build` command.

**Comment by lcasassa** [comment]
Let me take a look. Bus it should not need the target as without target it will use the last image

**Comment by lcasassa** [comment]
The image does not have sh, let me correct the travis file

**Comment by svenwltr** [comment]
The thing is, that Travis uses the Docker image for invoking a custom Makefile command. Therefore it needs all the build tools.

**Comment by lcasassa** [comment]
Yes, I just realised what you are saying. I already did the commit.

**Comment by lcasassa** [comment]
:)

**Pull request merged**
